### ISSUE TITLE
Mock-up of the UI 

### ISSUE THREAD

**Issue by shelemiah** [ryanmitchell/ti-ext-reports#2]
Below is a mock-up UI for your feedback and input. It has been structured with four (4) sections:

1. **Report Filters -**  Section where the end user select the type of report and other parameters needed to generate the report. This can be expanded to include more field selections/filters if needed. 
2. **Report Cards -** Section to display single value results (e.g. Total Sales) or a short list (e.g. Top 10 Customers)
3. **Report Graphs -** Section to display graphical reports if available.
4. **Report Table -** Section to display tabular reports with the ability to export/copy the data. 

![ti-report mock-up](https://user-images.githubusercontent.com/71740379/94352619-e5450980-002c-11eb-86bd-d48e2cdde0da.jpg)

**Comment by ryanmitchell** [comment]
Thanks for this, and the reports suggestions in the other issue. 

My initial approach has been for a ‘dashboard’ showing highlights of all reports which I had then intended to make it possible to click on to get into deeper on. 

This would make the report selection redundant as all reports would be initially available. 

If you are prepared to help develop the extension please fork and add code for me to review so that we can start adding to it.
